"""The committed v2 schema and the mobile client's calls stay in step with the application (ADR-0010 §4, §5).

These are cheap guards, not a UI test: they fail when someone changes a v2 route or DTO and forgets to re-export
`mobile-app/src/api/generated/openapi-v2.json`, or when the client calls a path the API does not serve.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED = REPO_ROOT / "mobile-app" / "src" / "api" / "generated" / "openapi-v2.json"
GENERATED_TYPES = REPO_ROOT / "mobile-app" / "src" / "api" / "generated" / "v2.ts"
CLIENT_DIR = REPO_ROOT / "mobile-app" / "src" / "api" / "v2"

# v2Request<T>("/path", ...), v2RequestFull<T>(`/path/${id}`, ...) and the admin-session variants (A9)
CALL = re.compile(r"v2(?:Admin)?Request(?:Full)?<[^>]*>\(\s*([`\"'])(.+?)\1", re.DOTALL)
TEMPLATE_PARAM = re.compile(r"\$\{[^}]+\}")


def _committed_schema() -> dict:
    assert GENERATED.is_file(), "run: py scripts/export_openapi.py"
    return json.loads(GENERATED.read_text(encoding="utf-8"))


def _client_paths() -> set[str]:
    paths: set[str] = set()
    for file in sorted(CLIENT_DIR.glob("*.api.ts")):
        for _quote, raw in CALL.findall(file.read_text(encoding="utf-8")):
            paths.add(TEMPLATE_PARAM.sub("{param}", raw))
    return paths


def _normalize(path: str) -> str:
    """`/api/v2/listings/{listing_id}` and the client's `/listings/{param}` compare the same."""
    without_prefix = path[len("/api/v2") :] if path.startswith("/api/v2") else path
    return re.sub(r"\{[^}]+\}", "{param}", without_prefix)


def test_committed_schema_matches_the_application() -> None:
    from scripts.export_openapi import build_schema, render

    current = render(build_schema())
    assert current == GENERATED.read_text(encoding="utf-8"), (
        "mobile-app/src/api/generated/openapi-v2.json is stale; run py scripts/export_openapi.py && npm run gen:api"
    )


def test_generated_types_exist_and_were_built_from_that_schema() -> None:
    assert GENERATED_TYPES.is_file(), "run: npm run gen:api (mobile-app)"
    text = GENERATED_TYPES.read_text(encoding="utf-8")
    assert "auto-generated by openapi-typescript" in text
    schema = _committed_schema()
    # a few operations from different owners must be present in the generated types
    for path in ("/api/v2/listings", "/api/v2/me/bookings", "/api/v2/public/listings/{token}"):
        assert path in schema["paths"], path
        assert f'"{path}"' in text, f"{path} missing from v2.ts; re-run npm run gen:api"


@pytest.mark.parametrize("client_path", sorted(_client_paths()))
def test_every_client_call_hits_a_real_v2_path(client_path: str) -> None:
    served = {_normalize(path) for path in _committed_schema()["paths"]}
    assert _normalize(client_path) in served, f"the mobile client calls {client_path}, which /api/v2 does not serve"


def test_client_layer_declares_no_hand_written_dto() -> None:
    """ADR-0010 §5: every v2 type in the client comes from the generated schema, not from a local interface."""
    for file in sorted(CLIENT_DIR.glob("*.ts")):
        text = file.read_text(encoding="utf-8")
        assert "interface " not in text, f"{file.name} declares an interface; use Schemas[...] from the generated types"
        for declaration in re.findall(r"export type (\w+) = ([^;]+);", text):
            name, value = declaration
            if name.endswith("DTO") or name.endswith("Create") or name.endswith("Request"):
                assert "Schemas[" in value or "|" in value, f"{file.name}: {name} is not taken from the contract"
