// Central icon surface. Re-exports lucide-react-native icons under the names the
// screens (ported from the web app's Phosphor aliases) already use, so screen
// code reads the same and the icon library stays swappable from one place.
export {
  House as Home,
  MapPin,
  Package,
  User,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  Star,
  ArrowRight,
  Truck,
  FileText,
  CircleAlert as AlertCircle,
  Send,
  Navigation,
  Phone,
  Inbox,
  Bell,
  Settings,
  Search,
  CreditCard,
  CheckCheck,
  Ban,
  Eye,
  Camera,
  Image as ImageIcon,
  ThumbsUp,
  Flag,
  Menu,
  X,
  Headphones,
  Tag,
  Zap,
  ClipboardList,
  CircleCheckBig as CheckCircle2,
  LogOut,
  Sun,
  Moon,
  Monitor,
  Vibrate,
  ToggleLeft,
  ToggleRight,
  TrendingUp,
  Shield,
  Info,
  RefreshCw,
  Route,
  BadgeCheck as SealCheck,
  BadgeAlert as SealWarning,
  Pencil,
  Trash2,
  Plus,
  Clock,
  Lock,
} from "lucide-react-native";
