"""First migration

Revision ID: ac62a9c9e9e2
Revises: 20260618_0014
Create Date: 2026-06-20 00:19:17.504678
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'ac62a9c9e9e2'
down_revision: str | None = '20260618_0014'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_entity_type_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('idx_bids_order_driver'), table_name='bids')
    op.drop_constraint(op.f('cities_name_key'), 'cities', type_='unique')
    op.drop_index(op.f('idx_driver_profiles_is_available'), table_name='driver_profiles')
    op.drop_index(op.f('idx_driver_profiles_verification_status'), table_name='driver_profiles')
    op.drop_index(op.f('idx_driver_routes_from_to'), table_name='driver_routes')
    op.drop_index(op.f('idx_driver_routes_status'), table_name='driver_routes')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_read_created'), table_name='notifications')
    op.drop_index(op.f('idx_order_offers_result'), table_name='order_offers')
    op.drop_index(op.f('idx_orders_from_to'), table_name='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_orders_from_to'), 'orders', ['from_city_id', 'to_city_id'], unique=False)
    op.create_index(op.f('idx_order_offers_result'), 'order_offers', ['result'], unique=False)
    op.create_index(op.f('ix_notifications_user_read_created'), 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('idx_driver_routes_status'), 'driver_routes', ['status'], unique=False)
    op.create_index(op.f('idx_driver_routes_from_to'), 'driver_routes', ['from_city_id', 'to_city_id'], unique=False)
    op.create_index(op.f('idx_driver_profiles_verification_status'), 'driver_profiles', ['verification_status'], unique=False)
    op.create_index(op.f('idx_driver_profiles_is_available'), 'driver_profiles', ['is_available'], unique=False)
    op.create_unique_constraint(op.f('cities_name_key'), 'cities', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_bids_order_driver'), 'bids', ['order_id', 'driver_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_entity_type_entity_id'), 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
