// Generate the native apps' Uzbek/Russian strings from the web client's dictionary.
//
//     node scripts/gen_native_strings.mjs           # writes android-app/ and ios-app/ string resources
//     node scripts/gen_native_strings.mjs --check   # exit 3 if a generated file is stale
//
// Source of truth: mobile-app/src/i18n/messages.ts (+ screens/*.ts) - one dictionary for web, Android and iOS, so
// a wording rule fixed once (spec §9.2, §21.2) is fixed everywhere. Uzbek is the default locale and the fallback.
// scripts/native_messages.json adds the few native-only strings; a key in both files is an error.
// Placeholders stay `{name}`; each platform's `t(key, "name" to value)` helper fills them.
//
// Outputs:
//   android-app/app/src/main/res/values/strings_shared.xml      (uz, default)
//   android-app/app/src/main/res/values-ru/strings_shared.xml   (ru)
//   android-app/.../i18n/generated/StringKeys.kt                (dotted key -> R.string id, for runtime keys like `error.<code>`)
//   ios-app/Elchi/Resources/Localizable.xcstrings               (key = dotted key, uz source + ru)

import { cpSync, existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = join(ROOT, "mobile-app", "src", "i18n");
const ANDROID_RES = join(ROOT, "android-app", "app", "src", "main", "res");
const KOTLIN_KEYS = join(ROOT, "android-app", "app", "src", "main", "kotlin", "uz", "elchi", "app", "i18n", "generated", "StringKeys.kt");
const XCSTRINGS = join(ROOT, "ios-app", "Elchi", "Resources", "Localizable.xcstrings");
const NATIVE_ONLY = join(ROOT, "scripts", "native_messages.json");
const HEADER = "Generated by scripts/gen_native_strings.mjs from mobile-app/src/i18n. Do not edit.";
/** Staff-only dictionaries of the web admin panel (`messageSources` names): the phone apps never show them. */
const STAFF_ONLY_SOURCES = new Set(["adminShell", "adminMarket", "adminMoney"]);

/** messages.ts uses extensionless imports (bundler style); Node needs `.ts`, so load a patched copy. */
async function loadMessages() {
  const work = mkdtempSync(join(tmpdir(), "elchi-i18n-"));
  try {
    cpSync(SOURCE, work, { recursive: true, filter: (p) => !p.endsWith(".test.ts") });
    for (const file of [join(work, "messages.ts"), ...readdirSync(join(work, "screens")).map((f) => join(work, "screens", f))]) {
      const text = readFileSync(file, "utf8").replace(/from "(\.\/screens\/[\w]+|\.\.\/messages)"/g, 'from "$1.ts"');
      writeFileSync(file, text);
    }
    writeFileSync(join(work, "package.json"), '{"type":"module"}');
    const module = await import(pathToFileURL(join(work, "messages.ts")).href);
    const kept = Object.entries(module.messageSources).filter(([name]) => !STAFF_ONLY_SOURCES.has(name));
    return Object.assign({}, ...kept.map(([, source]) => source));
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
}

/** `auth.otpLabel` -> `auth_otpLabel` (Android resource names allow [A-Za-z0-9_]). */
function resourceName(key) {
  return key.replace(/[^A-Za-z0-9_]/g, "_");
}

function androidEscape(text) {
  let out = text
    .replace(/\\/g, "\\\\")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/'/g, "\\'")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n");
  if (/^[@?]/.test(out)) out = "\\" + out;
  return out;
}

function androidXml(messages, keys, locale) {
  const lines = ['<?xml version="1.0" encoding="utf-8"?>', `<!-- ${HEADER} -->`, '<resources xmlns:tools="http://schemas.android.com/tools">'];
  for (const key of keys) {
    const text = messages[key][locale] || messages[key].uz;
    // `%` is literal text here (placeholders are `{name}`), so Android must not treat the string as a format.
    const formatted = text.includes("%") ? ' formatted="false"' : "";
    lines.push(`    <string name="${resourceName(key)}"${formatted}>${androidEscape(text)}</string>`);
  }
  lines.push("</resources>", "");
  return lines.join("\n");
}

function kotlinKeys(keys) {
  const lines = [
    `// ${HEADER}`,
    "package uz.elchi.app.i18n.generated",
    "",
    "import uz.elchi.app.R",
    "",
    "/** Dotted dictionary key -> string resource, for keys only known at runtime (`error.<code>`, statuses). */",
    "object StringKeys {",
    "    val byKey: Map<String, Int> = hashMapOf(",
  ];
  for (const key of keys) lines.push(`        "${key}" to R.string.${resourceName(key)},`);
  lines.push("    )", "}", "");
  return lines.join("\n");
}

function xcstrings(messages, keys) {
  const strings = {};
  for (const key of keys) {
    strings[key] = {
      extractionState: "manual",
      localizations: {
        ru: { stringUnit: { state: "translated", value: messages[key].ru || messages[key].uz } },
        uz: { stringUnit: { state: "translated", value: messages[key].uz } },
      },
    };
  }
  return JSON.stringify({ sourceLanguage: "uz", strings, version: "1.0" }, null, 2) + "\n";
}

const messages = await loadMessages();
const nativeOnly = JSON.parse(readFileSync(NATIVE_ONLY, "utf8"));
for (const [key, entry] of Object.entries(nativeOnly)) {
  if (key.startsWith("_")) continue;
  if (key in messages) throw new Error(`${key} is in both mobile-app/src/i18n and scripts/native_messages.json`);
  if (!entry.uz || !entry.ru) throw new Error(`${key} in scripts/native_messages.json needs both uz and ru`);
  messages[key] = { uz: entry.uz, ru: entry.ru };
}
const keys = Object.keys(messages).sort();

const names = new Map();
for (const key of keys) {
  const name = resourceName(key);
  if (names.has(name)) throw new Error(`resource name collision: ${key} and ${names.get(name)} -> ${name}`);
  names.set(name, key);
}

const files = new Map([
  [join(ANDROID_RES, "values", "strings_shared.xml"), androidXml(messages, keys, "uz")],
  [join(ANDROID_RES, "values-ru", "strings_shared.xml"), androidXml(messages, keys, "ru")],
  [KOTLIN_KEYS, kotlinKeys(keys)],
  [XCSTRINGS, xcstrings(messages, keys)],
]);

const check = process.argv.includes("--check");
const stale = [];
for (const [path, text] of files) {
  if (existsSync(path) && readFileSync(path, "utf8") === text) continue;
  if (check) {
    stale.push(path);
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, text);
  }
}
if (stale.length) {
  for (const path of stale) console.error(`stale: ${path.slice(ROOT.length + 1)}`);
  process.exit(3);
}
console.log(`${keys.length} strings (uz + ru)${check ? " - up to date" : ""}`);
