"""Generate the native apps' icons from the design kit's path data (scripts/native_icons.json).

    python3 scripts/gen_native_icons.py            # writes android-app/ and ios-app/ icon resources
    python3 scripts/gen_native_icons.py --check    # exit 3 if a generated file is stale

Every icon is a 24x24 stroked path (width 1.9, round caps/joins), drawn in one colour and tinted by the UI, so the
same shape serves light, dark, and every tone. Outputs:

- android-app/app/src/main/res/drawable/ic_<name>.xml   (VectorDrawable)
- android-app/.../ui/icons/ElchiIcon.kt                  (enum -> drawable)
- ios-app/Elchi/Resources/Icons.xcassets/<name>.imageset (template SVG, vector preserved)
- ios-app/Elchi/UI/ElchiIcon.swift                       (enum -> asset name)
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "scripts" / "native_icons.json"
ANDROID_DRAWABLE = ROOT / "android-app" / "app" / "src" / "main" / "res" / "drawable"
KOTLIN_ENUM = ROOT / "android-app" / "app" / "src" / "main" / "kotlin" / "uz" / "elchi" / "app" / "ui" / "icons" / "ElchiIcon.kt"
IOS_ASSETS = ROOT / "ios-app" / "Elchi" / "Resources" / "Icons.xcassets"
SWIFT_ENUM = ROOT / "ios-app" / "Elchi" / "UI" / "ElchiIcon.swift"
HEADER = "Generated by scripts/gen_native_icons.py from scripts/native_icons.json. Do not edit."
STROKE = 1.9


def snake(name: str) -> str:
    return re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\1", name).lower()


def camel(name: str) -> str:
    parts = snake(name).split("_")
    return parts[0] + "".join(p.title() for p in parts[1:])


def android_vector(path: str) -> str:
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- {HEADER} -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path
        android:pathData="{path}"
        android:strokeColor="#FF000000"
        android:strokeWidth="{STROKE}"
        android:strokeLineCap="round"
        android:strokeLineJoin="round" />
</vector>
"""


def ios_svg(path: str) -> str:
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" '
        f'stroke="#000000" stroke-width="{STROKE}" stroke-linecap="round" stroke-linejoin="round"><path d="{path}"/></svg>\n'
    )


def ios_contents(file: str) -> str:
    return json.dumps({
        "images": [{"filename": file, "idiom": "universal"}],
        "info": {"author": "xcode", "version": 1},
        "properties": {"preserves-vector-representation": True, "template-rendering-intent": "template"},
    }, indent=2) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="exit 3 if a generated file is stale")
    args = parser.parse_args(argv)

    icons = {k: v for k, v in json.loads(SOURCE.read_text(encoding="utf-8")).items() if not k.startswith("_")}
    files: dict[Path, str] = {}
    for name, path in icons.items():
        files[ANDROID_DRAWABLE / f"ic_{snake(name)}.xml"] = android_vector(path)
        imageset = IOS_ASSETS / f"{snake(name)}.imageset"
        files[imageset / f"{snake(name)}.svg"] = ios_svg(path)
        files[imageset / "Contents.json"] = ios_contents(f"{snake(name)}.svg")
    files[IOS_ASSETS / "Contents.json"] = json.dumps({"info": {"author": "xcode", "version": 1}}, indent=2) + "\n"

    kotlin = [f"// {HEADER}", "package uz.elchi.app.ui.icons", "", "import androidx.annotation.DrawableRes", "import uz.elchi.app.R", "",
              "/** The design kit's icons (24dp stroke), tinted by the caller. */",
              "enum class ElchiIcon(@DrawableRes val res: Int) {"]
    kotlin += [f"    {snake(n).upper()}(R.drawable.ic_{snake(n)})," for n in icons]
    kotlin[-1] = kotlin[-1].rstrip(",") + ","
    kotlin += ["}", ""]
    files[KOTLIN_ENUM] = "\n".join(kotlin)

    swift = [f"// {HEADER}", "", "/// The design kit's icons (24pt stroke, template images), tinted by the caller.",
             "public enum ElchiIcon: String, CaseIterable, Sendable {"]
    swift += [f"    case {camel(n)} = \"{snake(n)}\"" for n in icons]
    swift += ["}", ""]
    files[SWIFT_ENUM] = "\n".join(swift)

    stale = []
    for path, text in files.items():
        if path.exists() and path.read_text(encoding="utf-8") == text:
            continue
        if args.check:
            stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    if stale:
        for path in stale:
            print(f"stale: {path.relative_to(ROOT)}", file=sys.stderr)
        return 3
    print(f"{len(icons)} icons" + (" - up to date" if args.check else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
